import Foundation

/// Hand-drawn cat art shared by every cat breed. See docs/studynotch/pets.md
/// for the symbol legend. Outer outlines are added automatically.
enum CatArt {
    static let head = SpriteGrid(art: """
        .ee..............ee.
        .eee............eee.
        .ePee..........eePe.
        .ePPeaBBBBBBBBbePPe.
        .aaaaaBBsBBsBBbbbbb.
        aaaaaBBBsffsBBBbbbbb
        aaaaBBBBffffBBBBbbbb
        aaBBBBBffffffBBBBBbb
        BBBBBBffffffffBBBBBB
        sBBBBBfmmmmmmfBBBBBs
        BBBBBBmmmmmmmmBBBBBB
        .BBBBBBmmmmmmBBBBBB.
        .BBBBBBBmmmmBBBBBBB.
        ..SBBBBBBBBBBBBBBS..
        ....SSBBBBBBBBSS....
        """)

    /// British Shorthair: small ears set wide, full round cheeks.
    static let headRound = SpriteGrid(art: """
        ....................
        ..e..............e..
        .eee............eee.
        .ePeeaBBBBBBBBbbePe.
        .aaaaaBBBBBBBBbbbbb.
        aaaaaBBBBffBBBBbbbbb
        aaaaBBBBffffBBBBbbbb
        aaBBBBBffffffBBBBBbb
        BBBBBBffffffffBBBBBB
        BBBBBBfmmmmmmfBBBBBB
        BBBBBBmmmmmmmmBBBBBB
        BBBBBBBmmmmmmBBBBBBB
        .BBBBBBBmmmmBBBBBBB.
        ..SBBBBBBBBBBBBBBS..
        ....SSSBBBBBBSSS....
        """)

    static let faceOpen = SpriteGrid(art: """
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....LE........LE....
        ....EE........EE....
        ....EE........EE....
        ..PP...R.NN.R...PP..
        ........R..R........
        ....................
        ....................
        ....................
        """)

    static let bodySit = SpriteGrid(art: """
        .....BBBBBBBBBB.....
        ....aBBccccccBbb....
        ....aaccccccccbb....
        ...aaaccccccccbbs...
        ...saaBccccccBbbs...
        ...sBSBBccccBBSbb.tt
        ...BBSBBBBBBBBSbb.Bt
        ...aaSBBBBBBBBSBBBB.
        ...aaSBBBBBBBBSBBBB.
        ...SBppSBBBBSppBSS..
        ....pppp....pppp....
        """)
}
