import Foundation

/// Hand-drawn costume art. Body items (outfits, neck items) have one grid per
/// body family, the same size as and stamped at the same origin as that
/// family's body. Head items are 20 wide like every head and are placed by
/// the composer on each head's skull top. See docs/studynotch/pets.md.
enum CostumeArt {
    /// A grid drawn for each body family.
    struct BodyItem {
        let cat: SpriteGrid
        let dog: SpriteGrid
        let longDog: SpriteGrid
    }

    /// A hat-like item and the grid row that lands on the head's skull top.
    struct HeadItem {
        let grid: SpriteGrid
        let sitRow: Int
    }

    // MARK: Outfits

    static let scrubs = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....................
            ....CCCT....TCCC....
            ...CCCCCT..TCCCCC...
            ...CCCCCCTTCCCCCC...
            ...DCDCCCCCCTTTCD...
            ...DCDCCCCCCCCCCD...
            ...DDDDDDDDDDDDDD...
            """),
        dog: SpriteGrid(art: """
            ....................
            ....CCCT....TCCC....
            ...CCCCCT..TCCCCC...
            ...CCCCCCTTCCCCCC...
            ..DCCDCCCCCCTTTCCD..
            ..DCCDCCCCCCCCCCCD..
            ..DDDDDDDDDDDDDDDD..
            """),
        longDog: SpriteGrid(art: """
            ........................
            ....CCCCCCCCCCCCCCCCCC..
            ...CTCCDCCCCCCCCCCCCCCC.
            ...CCTCDCCCCCCCCCCCCCCC.
            ...DDDDDDDDDDDDDDDDDDDD.
            """)
    )

    static let whiteCoat = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....................
            ....UUUU....UUUU....
            ...UUUUUV..VUUUUU...
            ...UUUUUUVVUUUUUU...
            ...VUUUUUUVUUQUUV...
            ...VUUUUUUVUVVVUV...
            ...VUUUUUUVUUUUUV...
            ...VVVVVVVVVVVVVV...
            """),
        dog: SpriteGrid(art: """
            ....................
            ....UUUU....UUUU....
            ...UUUUUV..VUUUUU...
            ...UUUUUUVVUUUUUU...
            ..VUUUUUUUVUUQUUUV..
            ..VUUUUUUUVUVVVUUV..
            ..VUUUUUUUVUUUUUUV..
            ..VVVVVVVVVVVVVVVV..
            """),
        longDog: SpriteGrid(art: """
            ........................
            ....UUUUUUUUUUUUUUUUUU..
            ...UVUUVUUUUUUUUUUUUUUU.
            ...UUVUVUUUUUUUUUUUUUUU.
            ...UUUUVUUUUUUUUUUUUUUU.
            ...VVVVVVVVVVVVVVVVVVVV.
            """)
    )

    // MARK: Neck

    static let stethoscope = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....................
            .....G........G.....
            .....G........G.....
            ......G......G......
            .......GGGGGG.......
            ........MMMM........
            ........MZMM........
            """),
        dog: SpriteGrid(art: """
            ....................
            .....G........G.....
            .....G........G.....
            ......G......G......
            .......GGGGGG.......
            ........MMMM........
            ........MZMM........
            """),
        longDog: SpriteGrid(art: """
            ........................
            ...G.....G..............
            ...G.....G..............
            ....GGGGG...............
            .....MMMM...............
            .....MZMM...............
            """)
    )

    static let scarf = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....GGGGGGGGGGGG....
            ...JJJJJJJJJJJJJJ...
            ..........GGG.......
            ..........JJJ.......
            ..........GGG.......
            ..........G.G.......
            """),
        dog: SpriteGrid(art: """
            ....GGGGGGGGGGGG....
            ...JJJJJJJJJJJJJJ...
            ..........GGG.......
            ..........JJJ.......
            ..........GGG.......
            ..........G.G.......
            """),
        longDog: SpriteGrid(art: """
            ...GGGGGGG..............
            ..JJJJJJJJJ.............
            ......GGG...............
            ......JJJ...............
            ......G.G...............
            """)
    )

    // MARK: Face

    /// Round glasses ringing the cat face's eyes. Dark frames read on every
    /// fur color except the darkest, where the warm rim still frames the face.
    static let glassesCat = SpriteGrid(art: """
        ...QQQQ......QQQQ...
        ..Q....Q....Q....Q..
        ..Q....QQQQQQ....Q..
        ..Q....Q....Q....Q..
        ...QQQQ......QQQQ...
        """)

    /// The same glasses for the closer-set dog eyes. Lenses are wider than
    /// the eyes so the frames never touch the pupils and blur into them.
    static let glassesDog = SpriteGrid(art: """
        ....QQQQ....QQQQ....
        ...Q....Q..Q....Q...
        ...Q....QQQQ....Q...
        ...Q....Q..Q....Q...
        ....QQQQ....QQQQ....
        """)

    // MARK: Head

    static let surgicalCap = HeadItem(grid: SpriteGrid(art: """
        ......CCCCCCCC......
        .....CCTCCCCCTCC....
        ....CCCCCCTCCCCCC...
        ....CTCCCCCCCCTCC...
        ....DDDDDDDDDDDDD...
        """), sitRow: 4)

    static let beanie = HeadItem(grid: SpriteGrid(art: """
        .........JJ.........
        .......GGGGGG.......
        .....GGGGGGGGGG.....
        ....GGGGGGGGGGGG....
        ....JGJGJGJGJGJG....
        ....JJJJJJJJJJJJ....
        """), sitRow: 4)

    static let graduationCap = HeadItem(grid: SpriteGrid(art: """
        ........QQQQ........
        ....QQQQQQQQQQQQ....
        .QQQQQQQQYQQQQQQQQQ.
        ....QQQQQQQQQQQQY...
        ......QQQQQQQQ..Y...
        ......QQQQQQQQ..YY..
        """), sitRow: 5)

    static let headMirror = HeadItem(grid: SpriteGrid(art: """
        ......MMMM..........
        .....MZMMMM.........
        .....MMQQMM.........
        .....MMQQMM.........
        .....MMMMMM.........
        ...QQQMMMMQQQQQQQ...
        """), sitRow: 4)
}
