import Foundation

/// Hand-drawn cat art shared by every cat breed. See docs/study/pets.md
/// for the symbol legend. Outer outlines are added automatically.
enum CatArt {
    static let head = SpriteGrid(art: """
        .ee..............ee.
        .eee............eee.
        .ePee..........eePe.
        .ePPeaBBBBBBBBbePPe.
        .aaaaaBBsBBsBBbbbbb.
        aaaaaBBBsffsBBBbbbbb
        aaaaBBBBffffBBBBbbbb
        aaBBBBBffffffBBBBBbb
        BBBBBBffffffffBBBBBB
        sBBBBBfmmmmmmfBBBBBs
        BBBBBBmmmmmmmmBBBBBB
        .BBBBBBmmmmmmBBBBBB.
        .BBBBBBBmmmmBBBBBBB.
        ..SBBBBBBBBBBBBBBS..
        ....SSBBBBBBBBSS....
        """)

    /// British Shorthair: small rounded ears set wide, a taupe crown with
    /// faint ticking, and full round cheeks around a white muzzle and chin.
    static let headRound = SpriteGrid(art: """
        ....................
        .ee..............ee.
        .ePe.SSSSSSSSSS.ePe.
        .ePSSSSSASSASSSSSPe.
        .SSSSSSSASSASSSSSSS.
        SSSSSSSBBffBBSSSSSSS
        SBBBBBBBBffBBBBBBBBS
        BBBBBBBBBffBBBBBBBBB
        BBBBBBBBBBBBBBBBBBBB
        BBBBBBBmmBBmmBBBBBBB
        BBBBBBmmmmmmmmBBBBBB
        BBBBBmmmmmmmmmmBBBBB
        .BBBBBmmmmmmmmBBBBB.
        .BBBBBBmmmmmmBBBBBB.
        ...BBBBBmmmmBBBBB...
        """)

    /// British Shorthair face: the shared cat eyes (2x3, a highlight in the
    /// top corner) in blue and the shared nose and "w" mouth, with
    /// rosy cheeks.
    static let faceRound = SpriteGrid(art: """
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....LE........LE....
        ....EE........EE....
        ....EE........EE....
        ..PP...R.NN.R...PP..
        ........R..R........
        ....................
        ....................
        ....................
        """)

    static let faceOpen = SpriteGrid(art: """
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....LE........LE....
        ....EE........EE....
        ....EE........EE....
        ..PP...R.NN.R...PP..
        ........R..R........
        ....................
        ....................
        ....................
        """)

    static let bodySit = SpriteGrid(art: """
        .....BBBBBBBBBB.....
        ....aBBccccccBbb....
        ....aaccccccccbb....
        ...aaaccccccccbbs...
        ...saaBccccccBbbs...
        ...sBSBBccccBBSbb.tt
        ...BBSBBBBBBBBSbb.Bt
        ...aaSBBBBBBBBSBBBB.
        ...aaSBBBBBBBBSBBBB.
        ...SBppSBBBBSppBSS..
        ....pppp....pppp....
        """)

    /// British Shorthair sitting body: the `bodySit` frame (so every costume
    /// fits) widened a column to the right for a plump, round belly that sits
    /// centered under the head, with faint ticking on the flanks, a white
    /// chest and paws, and a thick ringed tail split off at column 18.
    static let bodyRound = SpriteGrid(art: """
        .....SBBBBBBBBS......
        ....SBBccccccBBS.....
        ...SSBccccccccBSS..tt
        ..SSBBccccccccBBSS.SS
        ..SsBBBccccccBBBsS.tt
        ..SSBBBBccccBBBBSS.SS
        ..SsBBBBBBBBBBBBsS.tt
        ..SSBBBBBBBBBBBBSSSSS
        ..SSsBBBBBBBBBBsSSS..
        ..SSBpppBBBBpppBSS...
        ...Spppp....ppppS....
        """)

    /// Sphynx: big bat-like ears flaring out from a narrow crown, forehead
    /// wrinkles drawn as short shade lines, sharp cheekbones, and a narrow
    /// muzzle. Hairless, so there is no ear tuft or stripe zone.
    static let headSphynx = SpriteGrid(art: """
        ee................ee
        ePe..............ePe
        ePPe............ePPe
        ePPPe.BBBBBBBB.ePPPe
        .ePPPBBSSBBSSBBPPPe.
        .ePPBBBBBSSBBBBBPPe.
        ..eBBBSSBBBBSSBBBe..
        ..BBBBBBBBBBBBBBBB..
        .BBBBBBBBBBBBBBBBBB.
        SBBBBBBBBBBBBBBBBBBS
        SBBBBBBmmmmmmBBBBBBS
        .SBBBBBmmmmmmBBBBBS.
        ..SBBBBBmmmmBBBBBS..
        ...SSBBBBBBBBBBSS...
        .....SSBBBBBBSS.....
        """)

    /// Sphynx face: big 3x3 lemon eyes with a slit pupil drawn in the
    /// outline color, a small nose over a "w" mouth, and rosy cheeks.
    static let faceSphynx = SpriteGrid(art: """
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....LOE......LOE....
        ....EOE......EOE....
        .....E...NN...E.....
        ..PP....R..R....PP..
        .........RR.........
        ....................
        ....................
        ....................
        """)

    /// Sphynx sitting body, the same 20x11 frame as `bodySit` so every
    /// costume fits: a lean chest with wrinkles at the neck, bony haunches,
    /// and a thin whip tail curling up.
    static let bodySphynx = SpriteGrid(art: """
        .....BBBBBBBBBB.....
        ....BSBccccccBSB...t
        ....BBcSccccScBB..t.
        ...BBBccSccSccBBB.t.
        ...SBBBccccccBBBS.t.
        ...SBSBBccccBBSBS.t.
        ...BBSBBBBBBBBSBB.t.
        ...BBSBBBBBBBBSBBBB.
        ...BBSBBBBBBBBSBBB..
        ...SBppSBBBBSppBSS..
        ....pppp....pppp....
        """)
}
