import Foundation

/// Hand-drawn cat art shared by every cat breed. See docs/study/pets.md
/// for the symbol legend. Outer outlines are added automatically.
enum CatArt {
    static let head = SpriteGrid(art: """
        .ee..............ee.
        .eee............eee.
        .ePee..........eePe.
        .ePPeaBBBBBBBBbePPe.
        .aaaaaBBsBBsBBbbbbb.
        aaaaaBBBsffsBBBbbbbb
        aaaaBBBBffffBBBBbbbb
        aaBBBBBffffffBBBBBbb
        BBBBBBffffffffBBBBBB
        sBBBBBfmmmmmmfBBBBBs
        BBBBBBmmmmmmmmBBBBBB
        .BBBBBBmmmmmmBBBBBB.
        .BBBBBBBmmmmBBBBBBB.
        ..SBBBBBBBBBBBBBBS..
        ....SSBBBBBBBBSS....
        """)

    /// British Shorthair: small rounded ears set wide, a taupe crown with
    /// faint ticking, and full round cheeks around a white muzzle and chin.
    static let headRound = SpriteGrid(art: """
        ....................
        .ee..............ee.
        .ePe.SSSSSSSSSS.ePe.
        .ePSSSSSASSASSSSSPe.
        .SSSSSSSASSASSSSSSS.
        SSSSSSSBBffBBSSSSSSS
        SBBBBBBBBffBBBBBBBBS
        BBBBBBBBBffBBBBBBBBB
        BBBBBBBBBBBBBBBBBBBB
        BBBBBBBmmBBmmBBBBBBB
        BBBBBBmmmmmmmmBBBBBB
        BBBBBmmmmmmmmmmBBBBB
        .BBBBBmmmmmmmmBBBBB.
        ..BBBBBmmmmmmBBBBB..
        ....BBBBmmmmBBBB....
        """)

    /// British Shorthair face: heavy half-closed lids over gray-green eyes
    /// (the lid is the eye color, the iris the eye light) for its
    /// unimpressed look, and a small nose over a flat mouth.
    static let faceRound = SpriteGrid(art: """
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....EEO......OEE....
        ....LL........LL....
        ....EE...NN...EE....
        ..P..............P..
        ........SSSS........
        ....................
        ....................
        ....................
        """)

    static let faceOpen = SpriteGrid(art: """
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....LE........LE....
        ....EE........EE....
        ....EE........EE....
        ..PP...R.NN.R...PP..
        ........R..R........
        ....................
        ....................
        ....................
        """)

    static let bodySit = SpriteGrid(art: """
        .....BBBBBBBBBB.....
        ....aBBccccccBbb....
        ....aaccccccccbb....
        ...aaaccccccccbbs...
        ...saaBccccccBbbs...
        ...sBSBBccccBBSbb.tt
        ...BBSBBBBBBBBSbb.Bt
        ...aaSBBBBBBBBSBBBB.
        ...aaSBBBBBBBBSBBBB.
        ...SBppSBBBBSppBSS..
        ....pppp....pppp....
        """)
}
