import Foundation

/// Hand-drawn costume art. Body items (outfits, neck items) have one grid per
/// body family, the same size as and stamped at the same origin as that
/// family's body. Head items are 20 wide like every head and are placed by
/// the composer on each head's skull top. See docs/study/pets.md.
enum CostumeArt {
    /// A grid drawn for each body family.
    struct BodyItem {
        let cat: SpriteGrid
        let dog: SpriteGrid
        let longDog: SpriteGrid
        /// Over the cat and dog walking torso (`WalkArt.catTorso`).
        let walk: SpriteGrid
        /// Over the dachshund walking torso (`WalkArt.longTorso`).
        let walkLong: SpriteGrid
    }

    /// A hat-like item and the grid row that lands on the head's skull top.
    struct HeadItem {
        let grid: SpriteGrid
        let sitRow: Int
    }

    // MARK: Outfits

    static let scrubs = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....................
            ....CCCT....TCCC....
            ...CCCCCT..TCCCCC...
            ...CCCCCCTTCCCCCC...
            ...DCDCCCCCCTTTCD...
            ...DCDCCCCCCCCCCD...
            ...DDDDDDDDDDDDDD...
            """),
        dog: SpriteGrid(art: """
            ....................
            ....CCCT....TCCC....
            ...CCCCCT..TCCCCC...
            ...CCCCCCTTCCCCCC...
            ..DCCDCCCCCCTTTCCD..
            ..DCCDCCCCCCCCCCCD..
            ..DDDDDDDDDDDDDDDD..
            """),
        longDog: SpriteGrid(art: """
            ........................
            ....CCCCCCCCCCCCCCCCCC..
            ...CTCCDCCCCCCCCCCCCCCC.
            ...CCTCDCCCCCCCCCCCCCCC.
            ...DDDDDDDDDDDDDDDDDDDD.
            """),
        walk: SpriteGrid(art: """
            ...CCCCCCCCCCCCCC.....
            ..CCCCCCCCCCCCCCCD....
            .TCCCCCCCCCCCCCCCD....
            .TCCCCCCCCCCCCCCCD....
            .CCCCCCCCCCCCCCCCD....
            .DDDDDDDDDDDDDDDDD....
            """),
        walkLong: SpriteGrid(art: """
            ...CCCCCCCCCCCCCCCC....
            ..CCCCCCCCCCCCCCCCCD...
            .TCCCCCCCCCCCCCCCCCD...
            .TCCCCCCCCCCCCCCCCCD...
            .DDDDDDDDDDDDDDDDDDD...
            """)
    )

    static let whiteCoat = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....................
            ....UUUU....UUUU....
            ...UUUUUV..VUUUUU...
            ...UUUUUUVVUUUUUU...
            ...VUUUUUUVUUQUUV...
            ...VUUUUUUVUVVVUV...
            ...VUUUUUUVUUUUUV...
            ...VVVVVVVVVVVVVV...
            """),
        dog: SpriteGrid(art: """
            ....................
            ....UUUU....UUUU....
            ...UUUUUV..VUUUUU...
            ...UUUUUUVVUUUUUU...
            ..VUUUUUUUVUUQUUUV..
            ..VUUUUUUUVUVVVUUV..
            ..VUUUUUUUVUUUUUUV..
            ..VVVVVVVVVVVVVVVV..
            """),
        longDog: SpriteGrid(art: """
            ........................
            ....UUUUUUUUUUUUUUUUUU..
            ...UVUUVUUUUUUUUUUUUUUU.
            ...UUVUVUUUUUUUUUUUUUUU.
            ...UUUUVUUUUUUUUUUUUUUU.
            ...VVVVVVVVVVVVVVVVVVVV.
            """),
        walk: SpriteGrid(art: """
            ...UUUUUUUUUUUUUUU....
            ..UUUUUUUUUUUUUUUUV...
            .UUUUUUUUUUUUUUUUUV...
            .UUUUUUUUUUUUUUUUUV...
            .UUUUUUUUUUUUUUUUUV...
            .UUUUUUUUUUUUUUUUUV...
            .VVVVVVVVVVVVVVVVVV...
            """),
        walkLong: SpriteGrid(art: """
            ...UUUUUUUUUUUUUUUUU...
            ..UUUUUUUUUUUUUUUUUUV..
            .UUUUUUUUUUUUUUUUUUUV..
            .UUUUUUUUUUUUUUUUUUUV..
            .UUUUUUUUUUUUUUUUUUUV..
            .VVVVVVVVVVVVVVVVVVVV..
            """)
    )

    // MARK: Neck

    static let stethoscope = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....................
            .....G........G.....
            .....G........G.....
            ......G......G......
            .......GGGGGG.......
            ........MMMM........
            ........MZMM........
            """),
        dog: SpriteGrid(art: """
            ....................
            .....G........G.....
            .....G........G.....
            ......G......G......
            .......GGGGGG.......
            ........MMMM........
            ........MZMM........
            """),
        longDog: SpriteGrid(art: """
            ........................
            ...G.....G..............
            ...G.....G..............
            ....GGGGG...............
            .....MMMM...............
            .....MZMM...............
            """),
        walk: SpriteGrid(art: """
            ..............G.......
            ..............G.......
            .............G........
            ............G.........
            ......................
            ...MMMM...............
            ...MZMM...............
            """),
        walkLong: SpriteGrid(art: """
            ..............G........
            .............G.........
            ............G..........
            .......................
            ...MMMM................
            ...MZMM................
            """)
    )

    static let scarf = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....GGGGGGGGGGGG....
            ...JJJJJJJJJJJJJJ...
            ..........GGG.......
            ..........JJJ.......
            ..........GGG.......
            ..........G.G.......
            """),
        dog: SpriteGrid(art: """
            ....GGGGGGGGGGGG....
            ...JJJJJJJJJJJJJJ...
            ..........GGG.......
            ..........JJJ.......
            ..........GGG.......
            ..........G.G.......
            """),
        longDog: SpriteGrid(art: """
            ...GGGGGGG..............
            ..JJJJJJJJJ.............
            ......GGG...............
            ......JJJ...............
            ......G.G...............
            """),
        walk: SpriteGrid(art: """
            .............GGG......
            .............JJJGG....
            ..............GJJJ....
            ..............G.......
            """),
        walkLong: SpriteGrid(art: """
            .............GGG.......
            .............JJJGG.....
            ..............GJJJ.....
            ..............G........
            """)
    )

    // MARK: Face

    /// Round glasses ringing the cat face's eyes. Dark frames read on every
    /// fur color except the darkest, where the warm rim still frames the face.
    static let glassesCat = SpriteGrid(art: """
        ...QQQQ......QQQQ...
        ..Q....Q....Q....Q..
        ..Q....QQQQQQ....Q..
        ..Q....Q....Q....Q..
        ...QQQQ......QQQQ...
        """)

    /// The same glasses for the closer-set dog eyes. Lenses are wider than
    /// the eyes so the frames never touch the pupils and blur into them.
    static let glassesDog = SpriteGrid(art: """
        ....QQQQ....QQQQ....
        ...Q....Q..Q....Q...
        ...Q....QQQQ....Q...
        ...Q....Q..Q....Q...
        ....QQQQ....QQQQ....
        """)

    // MARK: Head

    static let surgicalCap = HeadItem(grid: SpriteGrid(art: """
        ......CCCCCCCC......
        .....CCTCCCCCTCC....
        ....CCCCCCTCCCCCC...
        ....CTCCCCCCCCTCC...
        ....DDDDDDDDDDDDD...
        """), sitRow: 4)

    static let beanie = HeadItem(grid: SpriteGrid(art: """
        .........JJ.........
        .......GGGGGG.......
        .....GGGGGGGGGG.....
        ....GGGGGGGGGGGG....
        ....JGJGJGJGJGJG....
        ....JJJJJJJJJJJJ....
        """), sitRow: 4)

    static let graduationCap = HeadItem(grid: SpriteGrid(art: """
        ........QQQQ........
        ....QQQQQQQQQQQQ....
        .QQQQQQQQYQQQQQQQQQ.
        ....QQQQQQQQQQQQY...
        ......QQQQQQQQ..Y...
        ......QQQQQQQQ..YY..
        """), sitRow: 5)

    static let headMirror = HeadItem(grid: SpriteGrid(art: """
        ......MMMM..........
        .....MZMMMM.........
        .....MMQQMM.........
        .....MMQQMM.........
        .....MMMMMM.........
        ...QQQMMMMQQQQQQQ...
        """), sitRow: 4)
}

// MARK: - Fun head items

extension CostumeArt {
    /// A small gold crown on a navy band, so the gold never melts into
    /// orange or golden fur.
    static let tinyCrown = HeadItem(grid: SpriteGrid(art: """
        ......Y..YY..Y......
        ......YY.YY.YY......
        ......YYYYYYYY......
        ......YYHYYHYY......
        ......QQQQQQQQ......
        """), sitRow: 4)

    /// A polka-dot party cone with a red pom-pom and a gold trim that
    /// sits one row into the forehead, which gives the cone its height.
    static let partyHat = HeadItem(grid: SpriteGrid(art: """
        .........HH.........
        .........HH.........
        .........CC.........
        ........CYCC........
        ........CCCC........
        .......CCCCYC.......
        ......YYYYYYYY......
        """), sitRow: 5)

    /// A puffy chef's toque, wider at the top, on a band.
    static let chefHat = HeadItem(grid: SpriteGrid(art: """
        .....UUU.UU.UUU.....
        ....UUUUUUUUUUUU....
        ....UUUVUUUUVUUU....
        ....VUUUUUUUUUUV....
        .....VUUUUUUUUV.....
        .....UUUUUUUUUU.....
        .....VVVVVVVVVV.....
        """), sitRow: 5)

    /// A starry wizard cone whose tip flops to the side, on a wide brim
    /// pulled one row down over the brow.
    static let wizardHat = HeadItem(grid: SpriteGrid(art: """
        ............QQ......
        ..........QQQ.......
        .........QQQQ.......
        ........QQQYQ.......
        ........QQYYYQ......
        ......QQQQQYQQ......
        ...QQQQQQQQQQQQQQ...
        """), sitRow: 5)

    /// Tall white bunny ears with pink insides on a knit headband.
    static let bunnyEars = HeadItem(grid: SpriteGrid(art: """
        .....UU......UU.....
        ....UPPU....UPPU....
        ....UPPU....UPPU....
        ....UPPU....UPPU....
        .....UU......UU.....
        ....GGGGGGGGGGGG....
        """), sitRow: 5)
}

// MARK: - Fun head items, second set

extension CostumeArt {
    /// A pointed witch hat with a crooked tip, a red band with a gold
    /// buckle, and a flat brim. Straighter and plainer than the wizard hat,
    /// so the two read apart.
    static let witchHat = HeadItem(grid: SpriteGrid(art: """
        ...........QQ.......
        .........QQQ........
        ........QQQQ........
        .......QQQQQQ.......
        ......QQQQQQQQ......
        .....HHHHYYHHHH.....
        .QQQQQQQQQQQQQQQQQQ.
        """), sitRow: 5)

    /// A leather cowboy hat: a dented crown on a navy band and a wide brim
    /// that curls up at both ends.
    static let cowboyHat = HeadItem(grid: SpriteGrid(art: """
        ......III..III......
        ......IIIIIIII......
        .I....IIIIIIII....I.
        .II...QQQQQQQQ...II.
        ..IIIIIIIIIIIIIIII..
        ....IIIIIIIIIIII....
        """), sitRow: 4)

    /// Three little flowers on a leafy vine laid across the crown.
    static let flowerCrown = HeadItem(grid: SpriteGrid(art: """
        .....H...ZZ...H.....
        ....HYH.ZYYZ.HYH....
        ...FFHFFFZZFFFHFF...
        """), sitRow: 2)

    /// A green frog hood with two bulging eyes on top and a wide smile
    /// across the forehead.
    static let frogHat = HeadItem(grid: SpriteGrid(art: """
        ....FFFF....FFFF....
        ...FUUUUF..FUUUUF...
        ...FUQQUF..FUQQUF...
        ...FFFFFFFFFFFFFF...
        ...FFFFQFFFFQFFFF...
        ...FFFFFQQQQFFFFF...
        """), sitRow: 4)

    /// A navy headband with a metal plate, tied at the side so the two
    /// tails hang past the ear.
    static let ninjaHeadband = HeadItem(grid: SpriteGrid(art: """
        ...QQQQQMMMMQQQQQ...
        ...QQQQQMZMMQQQQQQQ.
        .................Q.Q
        """), sitRow: 0)
}
