import Foundation

/// Hand-drawn costume art. Body items (outfits, neck items) have one grid per
/// body family, the same size as and stamped at the same origin as that
/// family's body. Head items are 20 wide like every head and are placed by
/// the composer on each head's skull top. See docs/study/pets.md.
enum CostumeArt {
    /// A grid drawn for each body family.
    struct BodyItem {
        let cat: SpriteGrid
        let dog: SpriteGrid
        let longDog: SpriteGrid
        /// Over the cat and dog walking torso (`WalkArt.catTorso`).
        let walk: SpriteGrid
        /// Over the dachshund walking torso (`WalkArt.longTorso`).
        let walkLong: SpriteGrid
        /// Rows every grid reaches above its body's top row, for parts that
        /// stick up out of the silhouette, such as spikes along the back.
        var rise = 0
    }

    /// A face item, one grid for cat faces and one for dog faces, and the
    /// grid row that lands on the head's eye row.
    struct FaceItem {
        let cat: SpriteGrid
        let dog: SpriteGrid
        let eyeRow: Int
    }

    /// A hat-like item and the grid row that lands on the head's skull top.
    struct HeadItem {
        let grid: SpriteGrid
        let sitRow: Int
    }

    // MARK: Outfits

    static let scrubs = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....................
            ....CCCT....TCCC....
            ...CCCCCT..TCCCCC...
            ...CCCCCCTTCCCCCC...
            ...DCDCCCCCCTTTCD...
            ...DCDCCCCCCCCCCD...
            ...DDDDDDDDDDDDDD...
            """),
        dog: SpriteGrid(art: """
            ....................
            ....CCCT....TCCC....
            ...CCCCCT..TCCCCC...
            ...CCCCCCTTCCCCCC...
            ..DCCDCCCCCCTTTCCD..
            ..DCCDCCCCCCCCCCCD..
            ..DDDDDDDDDDDDDDDD..
            """),
        longDog: SpriteGrid(art: """
            ........................
            ....CCCCCCCCCCCCCCCCCC..
            ...CTCCDCCCCCCCCCCCCCCC.
            ...CCTCDCCCCCCCCCCCCCCC.
            ...DDDDDDDDDDDDDDDDDDDD.
            """),
        walk: SpriteGrid(art: """
            ...CCCCCCCCCCCCCC.....
            ..CCCCCCCCCCCCCCCD....
            .TCCCCCCCCCCCCCCCD....
            .TCCCCCCCCCCCCCCCD....
            .CCCCCCCCCCCCCCCCD....
            .DDDDDDDDDDDDDDDDD....
            """),
        walkLong: SpriteGrid(art: """
            ...CCCCCCCCCCCCCCCC....
            ..CCCCCCCCCCCCCCCCCD...
            .TCCCCCCCCCCCCCCCCCD...
            .TCCCCCCCCCCCCCCCCCD...
            .DDDDDDDDDDDDDDDDDDD...
            """)
    )

    static let whiteCoat = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....................
            ....UUUU....UUUU....
            ...UUUUUV..VUUUUU...
            ...UUUUUUVVUUUUUU...
            ...VUUUUUUVUUQUUV...
            ...VUUUUUUVUVVVUV...
            ...VUUUUUUVUUUUUV...
            ...VVVVVVVVVVVVVV...
            """),
        dog: SpriteGrid(art: """
            ....................
            ....UUUU....UUUU....
            ...UUUUUV..VUUUUU...
            ...UUUUUUVVUUUUUU...
            ..VUUUUUUUVUUQUUUV..
            ..VUUUUUUUVUVVVUUV..
            ..VUUUUUUUVUUUUUUV..
            ..VVVVVVVVVVVVVVVV..
            """),
        longDog: SpriteGrid(art: """
            ........................
            ....UUUUUUUUUUUUUUUUUU..
            ...UVUUVUUUUUUUUUUUUUUU.
            ...UUVUVUUUUUUUUUUUUUUU.
            ...UUUUVUUUUUUUUUUUUUUU.
            ...VVVVVVVVVVVVVVVVVVVV.
            """),
        walk: SpriteGrid(art: """
            ...UUUUUUUUUUUUUUU....
            ..UUUUUUUUUUUUUUUUV...
            .UUUUUUUUUUUUUUUUUV...
            .UUUUUUUUUUUUUUUUUV...
            .UUUUUUUUUUUUUUUUUV...
            .UUUUUUUUUUUUUUUUUV...
            .VVVVVVVVVVVVVVVVVV...
            """),
        walkLong: SpriteGrid(art: """
            ...UUUUUUUUUUUUUUUUU...
            ..UUUUUUUUUUUUUUUUUUV..
            .UUUUUUUUUUUUUUUUUUUV..
            .UUUUUUUUUUUUUUUUUUUV..
            .UUUUUUUUUUUUUUUUUUUV..
            .VVVVVVVVVVVVVVVVVVVV..
            """)
    )

    // MARK: Neck

    static let stethoscope = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....................
            .....G........G.....
            .....G........G.....
            ......G......G......
            .......GGGGGG.......
            ........MMMM........
            ........MZMM........
            """),
        dog: SpriteGrid(art: """
            ....................
            .....G........G.....
            .....G........G.....
            ......G......G......
            .......GGGGGG.......
            ........MMMM........
            ........MZMM........
            """),
        longDog: SpriteGrid(art: """
            ........................
            ...G.....G..............
            ...G.....G..............
            ....GGGGG...............
            .....MMMM...............
            .....MZMM...............
            """),
        walk: SpriteGrid(art: """
            ..............G.......
            ..............G.......
            .............G........
            ............G.........
            ......................
            ...MMMM...............
            ...MZMM...............
            """),
        walkLong: SpriteGrid(art: """
            ..............G........
            .............G.........
            ............G..........
            .......................
            ...MMMM................
            ...MZMM................
            """)
    )

    static let scarf = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....GGGGGGGGGGGG....
            ...JJJJJJJJJJJJJJ...
            ..........GGG.......
            ..........JJJ.......
            ..........GGG.......
            ..........G.G.......
            """),
        dog: SpriteGrid(art: """
            ....GGGGGGGGGGGG....
            ...JJJJJJJJJJJJJJ...
            ..........GGG.......
            ..........JJJ.......
            ..........GGG.......
            ..........G.G.......
            """),
        longDog: SpriteGrid(art: """
            ...GGGGGGG..............
            ..JJJJJJJJJ.............
            ......GGG...............
            ......JJJ...............
            ......G.G...............
            """),
        walk: SpriteGrid(art: """
            .............GGG......
            .............JJJGG....
            ..............GJJJ....
            ..............G.......
            """),
        walkLong: SpriteGrid(art: """
            .............GGG.......
            .............JJJGG.....
            ..............GJJJ.....
            ..............G........
            """)
    )

    // MARK: Face

    /// Round glasses ringing the eyes. Dark frames read on every fur color
    /// except the darkest, where the warm rim still frames the face. The dog
    /// lenses are wider than the closer-set eyes so the frames never touch
    /// the pupils and blur into them.
    static let roundGlasses = FaceItem(cat: SpriteGrid(art: """
        ...QQQQ......QQQQ...
        ..Q....Q....Q....Q..
        ..Q....QQQQQQ....Q..
        ..Q....Q....Q....Q..
        ...QQQQ......QQQQ...
        """), dog: SpriteGrid(art: """
        ....QQQQ....QQQQ....
        ...Q....Q..Q....Q...
        ...Q....QQQQ....Q...
        ...Q....Q..Q....Q...
        ....QQQQ....QQQQ....
        """), eyeRow: 1)

    // MARK: Head

    static let surgicalCap = HeadItem(grid: SpriteGrid(art: """
        ......CCCCCCCC......
        .....CCTCCCCCTCC....
        ....CCCCCCTCCCCCC...
        ....CTCCCCCCCCTCC...
        ....DDDDDDDDDDDDD...
        """), sitRow: 4)

    static let beanie = HeadItem(grid: SpriteGrid(art: """
        .........JJ.........
        .......GGGGGG.......
        .....GGGGGGGGGG.....
        ....GGGGGGGGGGGG....
        ....JGJGJGJGJGJG....
        ....JJJJJJJJJJJJ....
        """), sitRow: 4)

    static let graduationCap = HeadItem(grid: SpriteGrid(art: """
        ........QQQQ........
        ....QQQQQQQQQQQQ....
        .QQQQQQQQYQQQQQQQQQ.
        ....QQQQQQQQQQQQY...
        ......QQQQQQQQ..Y...
        ......QQQQQQQQ..YY..
        """), sitRow: 5)

    static let headMirror = HeadItem(grid: SpriteGrid(art: """
        ......MMMM..........
        .....MZMMMM.........
        .....MMQQMM.........
        .....MMQQMM.........
        .....MMMMMM.........
        ...QQQMMMMQQQQQQQ...
        """), sitRow: 4)
}

// MARK: - Fun head items

extension CostumeArt {
    /// A small gold crown on a navy band, so the gold never melts into
    /// orange or golden fur.
    static let tinyCrown = HeadItem(grid: SpriteGrid(art: """
        ......Y..YY..Y......
        ......YY.YY.YY......
        ......YYYYYYYY......
        ......YYHYYHYY......
        ......QQQQQQQQ......
        """), sitRow: 4)

    /// A polka-dot party cone with a red pom-pom and a gold trim that
    /// sits one row into the forehead, which gives the cone its height.
    static let partyHat = HeadItem(grid: SpriteGrid(art: """
        .........HH.........
        .........HH.........
        .........CC.........
        ........CYCC........
        ........CCCC........
        .......CCCCYC.......
        ......YYYYYYYY......
        """), sitRow: 5)

    /// A puffy chef's toque, wider at the top, on a band.
    static let chefHat = HeadItem(grid: SpriteGrid(art: """
        .....UUU.UU.UUU.....
        ....UUUUUUUUUUUU....
        ....UUUVUUUUVUUU....
        ....VUUUUUUUUUUV....
        .....VUUUUUUUUV.....
        .....UUUUUUUUUU.....
        .....VVVVVVVVVV.....
        """), sitRow: 5)

    /// A starry wizard cone whose tip flops to the side, on a wide brim
    /// pulled one row down over the brow.
    static let wizardHat = HeadItem(grid: SpriteGrid(art: """
        ............QQ......
        ..........QQQ.......
        .........QQQQ.......
        ........QQQYQ.......
        ........QQYYYQ......
        ......QQQQQYQQ......
        ...QQQQQQQQQQQQQQ...
        """), sitRow: 5)

    /// Tall white bunny ears with pink insides on a knit headband.
    static let bunnyEars = HeadItem(grid: SpriteGrid(art: """
        .....UU......UU.....
        ....UPPU....UPPU....
        ....UPPU....UPPU....
        ....UPPU....UPPU....
        .....UU......UU.....
        ....GGGGGGGGGGGG....
        """), sitRow: 5)
}

// MARK: - Fun head items, second set

extension CostumeArt {
    /// A pointed witch hat with a crooked tip, a red band with a gold
    /// buckle, and a flat brim. Straighter and plainer than the wizard hat,
    /// so the two read apart.
    static let witchHat = HeadItem(grid: SpriteGrid(art: """
        ...........QQ.......
        .........QQQ........
        ........QQQQ........
        .......QQQQQQ.......
        ......QQQQQQQQ......
        .....HHHHYYHHHH.....
        .QQQQQQQQQQQQQQQQQQ.
        """), sitRow: 5)

    /// A leather cowboy hat: a dented crown on a navy band and a wide brim
    /// that curls up at both ends.
    static let cowboyHat = HeadItem(grid: SpriteGrid(art: """
        ......III..III......
        ......IIIIIIII......
        .I....IIIIIIII....I.
        .II...QQQQQQQQ...II.
        ..IIIIIIIIIIIIIIII..
        ....IIIIIIIIIIII....
        """), sitRow: 4)

    /// Three little flowers on a leafy vine laid across the crown.
    static let flowerCrown = HeadItem(grid: SpriteGrid(art: """
        .....H...ZZ...H.....
        ....HYH.ZYYZ.HYH....
        ...FFHFFFZZFFFHFF...
        """), sitRow: 2)

    /// A green frog hood with two bulging eyes on top and a wide smile
    /// across the forehead.
    static let frogHat = HeadItem(grid: SpriteGrid(art: """
        ....FFFF....FFFF....
        ...FUUUUF..FUUUUF...
        ...FUQQUF..FUQQUF...
        ...FFFFFFFFFFFFFF...
        ...FFFFQFFFFQFFFF...
        ...FFFFFQQQQFFFFF...
        """), sitRow: 4)

    /// A navy headband with a metal plate, tied at the side so the two
    /// tails hang past the ear.
    static let ninjaHeadband = HeadItem(grid: SpriteGrid(art: """
        ...QQQQQMMMMQQQQQ...
        ...QQQQQMZMMQQQQQQQ.
        .................Q.Q
        """), sitRow: 0)
}

// MARK: - Fun face and mask items

extension CostumeArt {
    /// Wide dark shades with a white glint on each lens. The lenses cover
    /// the eyes completely, which is the whole joke.
    static let coolSunglasses = FaceItem(cat: SpriteGrid(art: """
        .QQQQQQQQQQQQQQQQQQ.
        ..QZZQQQ....QZZQQQ..
        ..QZQQQQ....QZQQQQ..
        ...QQQQ......QQQQ...
        """), dog: SpriteGrid(art: """
        ...QQQQQQQQQQQQQQ...
        ....QZQQQ..QZQQQ....
        ....QQQQQ..QQQQQ....
        .....QQQ....QQQ.....
        """), eyeRow: 1)

    /// A navy tricorn with upturned sides, a white skull badge, and gold
    /// trim along the brim.
    static let pirateHat = HeadItem(grid: SpriteGrid(art: """
        ........QQQQ........
        .QQ...QQQQQQQQ...QQ.
        .QQQQQQQQUUQQQQQQQQ.
        ..QQQQQQQUUQQQQQQQ..
        ...YYYYYYYYYYYYYY...
        """), sitRow: 4)

    /// An eyepatch over the right eye, its strap running up under the hat.
    static let eyepatch = FaceItem(cat: SpriteGrid(art: """
        .....QQ.............
        .......QQQ..........
        ..........QQQQQQ....
        ............QQQQQ...
        ............QQQQQ...
        .............QQQ....
        """), dog: SpriteGrid(art: """
        ....................
        .......QQQ..........
        ..........QQQQ......
        ...........QQQQ.....
        ...........QQQQ.....
        ............QQ......
        """), eyeRow: 3)

    /// Spiky white hair standing straight up, shaded on one side of each
    /// spike, with a fringe that falls onto the blindfold.
    static let spikyHair = HeadItem(grid: SpriteGrid(art: """
        ...U.....U....U.....
        ...UU...UU...UUU..U.
        ...UUV.UUUV.UUUUVUU.
        ..UUUUVUUUUVUUUUUUV.
        .UUUUUUUUUUUUUUUUUU.
        .UUUUUUUUUUUUUUUUUU.
        .UUVUUUUVUUUUVUUUUU.
        ..UV.UUV..UUV..UV...
        """), sitRow: 5)

    /// A dark blindfold tied over both eyes, open under the nose bridge.
    static let blindfold = FaceItem(cat: SpriteGrid(art: """
        .QQQQQQQQQQQQQQQQQQ.
        .QQQQQQQQQQQQQQQQQQ.
        ..QQQQQQ....QQQQQQ..
        """), dog: SpriteGrid(art: """
        .QQQQQQQQQQQQQQQQQQ.
        .QQQQQQQQQQQQQQQQQQ.
        ..QQQQQQ....QQQQQQ..
        """), eyeRow: 0)
}

// MARK: - Fun head and neck items, third set

extension CostumeArt {
    /// A white space helmet with its dark visor flipped up over the brow
    /// (a glint shows it is glass), an antenna with a red light, a metal
    /// collar ring, and side pods over the ears, so it reads as a helmet
    /// rather than a cap. A gold visor read as a hard hat.
    static let astronautHelmet = HeadItem(grid: SpriteGrid(art: """
        .........H..........
        .......UUMUUU.......
        .....UUUUUUUUUV.....
        ....UUQQQQQQQQUV....
        ...UUQZZQQQQQQQUV...
        ...UUQZQQQQQQQQUV...
        ..MMMMMMMMMMMMMMMM..
        .MQM............MQM.
        .MMM............MMM.
        """), sitRow: 5)

    /// Chunky over-ear headphones: a navy band over the crown and big
    /// red cups with metal grilles over the ears.
    static let chunkyHeadphones = HeadItem(grid: SpriteGrid(art: """
        ....QQQQQQQQQQQQ....
        ...Q............Q...
        ..Q..............Q..
        HHHH............HHHH
        HMMH............HMMH
        HMMH............HMMH
        HHHH............HHHH
        """), sitRow: 1)

    /// A red bow tie under the chin with a darker knot.
    static let bowTie = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....................
            ......HH....HH......
            ......HHHJJHHH......
            ......HH....HH......
            """),
        dog: SpriteGrid(art: """
            ....................
            ......HH....HH......
            ......HHHJJHHH......
            ......HH....HH......
            """),
        longDog: SpriteGrid(art: """
            ........................
            ..HH....HH..............
            ..HHHJJHHH..............
            ..HH....HH..............
            """),
        walk: SpriteGrid(art: """
            ......................
            ......................
            ......................
            ......................
            ......................
            ..HH.HH...............
            ..HHJHH...............
            ..HH.HH...............
            """),
        walkLong: SpriteGrid(art: """
            .......................
            .......................
            .......................
            .......................
            ..HH.HH................
            ..HHJHH................
            ..HH.HH................
            """)
    )
}

// MARK: - Fun outfits

extension CostumeArt {
    /// A zip-up hoodie in the knit color with the hood bunched at the collar,
    /// a metal zipper, a kangaroo pocket, and the hood lying on the back when
    /// seen from the side. White drawstrings read as a face from the front.
    static let cozyHoodie = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....................
            ....GJJJJJJJJJJG....
            ...GGGGGGMGGGGGGG...
            ...GGGGGGMGGGGGGG...
            ...GGGGGGMGGGGGGG...
            ...GGJJJJMJJJJGGG...
            ...GGGJJJMJJJGGGG...
            ...JJJJJJJJJJJJJJ...
            """),
        dog: SpriteGrid(art: """
            ....................
            ....GJJJJJJJJJJG....
            ...GGGGGGMGGGGGGG...
            ...GGGGGGMGGGGGGG...
            ..GGGGGGGMGGGGGGGG..
            ..GGGJJJJMJJJJGGGG..
            ..GGGGJJJMJJJGGGGG..
            ..JJJJJJJJJJJJJJJJ..
            """),
        longDog: SpriteGrid(art: """
            ........................
            ....GGGGGGJJJJGGGGGGGG..
            ...JMGGGGJGGGGJGGGGGGGG.
            ...JMGGGGGJJJJGGGGGGGGG.
            ...JJJJJJJJJJJJJJJJJJJJ.
            """),
        walk: SpriteGrid(art: """
            ...GGGGGGGGGGJJJJGG...
            ..GGGGGGGGGGJGGGGJGG..
            .GGGGGGGGGGGGJJJJGGGG.
            .GGGGGGGGGGGGGGGGGGGG.
            .GGGGGGGGGGGGGGGGGGGG.
            .JJJJJJJJJJJJJJJJJJJJ.
            """),
        walkLong: SpriteGrid(art: """
            ...GGGGGGGGGGGJJJJGGG..
            ..GGGGGGGGGGGJGGGGJGGG.
            .GGGGGGGGGGGGGJJJJGGGG.
            .GGGGGGGGGGGGGGGGGGGGG.
            .JJJJJJJJJJJJJJJJJJJJJ.
            """)
    )

    /// A red cape fastened with a gold clasp at the collar. From the front it
    /// drapes over the shoulders and falls past both sides of the body; from
    /// the side it streams back over the rump.
    static let superheroCape = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....................
            ....................
            ...HHHHH.YY.HHHHH...
            ..HHH..........HHH..
            ..HH............HH..
            ..HH............HH..
            .HHH............HHH.
            .HHH............HHH.
            .HHH............HHH.
            .HHY............YHH.
            """),
        dog: SpriteGrid(art: """
            ....................
            ....................
            ...HHHHH.YY.HHHHH...
            ..HHH..........HHH..
            ..HH............HH..
            .HHH............HHH.
            .HHH............HHH.
            .HHH............HHH.
            .HHH............HHH.
            .HHY............YHH.
            """),
        longDog: SpriteGrid(art: """
            .................HHH....
            ........................
            ........YHHHHHHHHHHH....
            .........HHHHHHHHHHHHH..
            ..........HHHHHHHHHHHHH.
            ............HHHHHHH.HH..
            """),
        walk: SpriteGrid(art: """
            ..............HHH.......
            ...........HHHHHHHHHH...
            ..........HHHHHHHHHHHHH.
            ...........HHHHHHHHHHHH.
            .............HHHHHHH.HH.
            ...............HHH......
            """),
        walkLong: SpriteGrid(art: """
            ...............HHH......
            ............HHHHHHHHHH..
            ...........HHHHHHHHHHHHH
            ............HHHHHHHHHHHH
            ..............HHHHHHH.HH
            ................HHH.....
            """),
        rise: 1
    )

    /// A green dinosaur suit with a gold belly and gold spikes down the back.
    /// Its hood is `dinosaurHood`.
    static let dinosaurHoodie = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....................
            ....................
            ....................
            ....FFFFYYYYFFFF....
            ...FFFFYYYYYYFFFF...
            ...FFFFYYYYYYFFFF...
            ...FFFFYYYYYYFFFF...
            ...FFFFFYYYYFFFFF...
            ...FFFFFFFFFFFFFF...
            """),
        dog: SpriteGrid(art: """
            ....................
            ....................
            ....................
            ....FFFFYYYYFFFF....
            ...FFFFYYYYYYFFFF...
            ...FFFFYYYYYYFFFF...
            ..FFFFFYYYYYYFFFFF..
            ..FFFFFFYYYYFFFFFF..
            ..FFFFFFFFFFFFFFFF..
            """),
        longDog: SpriteGrid(art: """
            ..............Y..Y..Y...
            .............YY.YY.YY...
            ........................
            ....FFFFFFFFFFFFFFFFFF..
            ...YYYYFFFFFFFFFFFFFFFF.
            ...YYYYFFFFFFFFFFFFFFFF.
            ...FFFFFFFFFFFFFFFFFFFF.
            """),
        walk: SpriteGrid(art: """
            ...............Y..Y...
            ..............YY.YY...
            ...FFFFFFFFFFFFFFFF...
            ..FFFFFFFFFFFFFFFFFF..
            .FFFFFFFFFFFFFFFFFFFF.
            .FFFFFFFFFFFFFFFFFFFF.
            .YYYYFFFFFFFFFFFFFFFF.
            .YYYYYFFFFFFFFFFFFFFF.
            """),
        walkLong: SpriteGrid(art: """
            ...............Y..Y....
            ..............YY.YY....
            ...FFFFFFFFFFFFFFFFFF..
            ..FFFFFFFFFFFFFFFFFFFF.
            .YYYFFFFFFFFFFFFFFFFFF.
            .YYYYFFFFFFFFFFFFFFFFF.
            .FFFFFFFFFFFFFFFFFFFFF.
            """),
        rise: 2
    )

    /// A starry navy robe to match the wizard hat, with gold trim down the
    /// front and a gold hem that flares a little above the paws.
    static let wizardRobe = BodyItem(
        cat: SpriteGrid(art: """
            ....................
            ....................
            ....QQQY....YQQQ....
            ...QQYQQY..YQQQQQ...
            ...QQQQQQYYQQQQYQ...
            ...QQQQQQQYQQQQQQ...
            ...QQYQQQQYQQQQQQ...
            ..QQQQQQQQYQQQQYQQ..
            ..QQQQQQQQYQQQQQQQ..
            ..YYYYYYYYYYYYYYYY..
            """),
        dog: SpriteGrid(art: """
            ....................
            ....QQQY....YQQQ....
            ...QQYQQY..YQQQQQ...
            ...QQQQQQYYQQQQYQ...
            ..QQQQQQQQYQQQQQQQ..
            ..QQQYQQQQYQQQQQQQ..
            ..QQQQQQQQYQQQQYQQ..
            ..QQQQQQQQYQQQQQQQ..
            ..YYYYYYYYYYYYYYYYY.
            """),
        longDog: SpriteGrid(art: """
            ........................
            ....QQQQQQQQQQQQQQQQQQ..
            ...QQQYQQQQQYQQQQQQYQQQ.
            ...QQQYQQYQQQQQQYQQQQQQ.
            ...YYYYYYYYYYYYYYYYYYYY.
            """),
        walk: SpriteGrid(art: """
            ...QQQQQQQQQQQQQQQQ...
            ..QQQQQQQQQQQQQQYQQQ..
            .QQQQQQQQQQQQYQQQQQQQ.
            .QQQQQQQQQQQQQQQQYQQQ.
            .QQQQQQQQQQQQQYQQQQQQ.
            .QQQQQQQQQQQQQQQQQQQQ.
            .QQQQQQQQQQQQQQQQQQQQ.
            .YYYYYYYYYYYYYYYYYYYY.
            """),
        walkLong: SpriteGrid(art: """
            ...QQQQQQQQQQQQQQQQQ...
            ..QQQQQQQQQQQQQQYQQQQ..
            .QQQQQQQQQQQQYQQQQQQQQ.
            .QQQQQQQQQQQQQQQQYQQQQ.
            .QQQQQQQQQQQQQQQQQQQQQ.
            .YYYYYYYYYYYYYYYYYYYYY.
            """)
    )

    /// The dinosaur hood: gold spikes along the crown, little white teeth
    /// along the brim, and sides that frame the face, so it reads as a hood.
    static let dinosaurHood = HeadItem(grid: SpriteGrid(art: """
        ......Y..YY..Y......
        .....YYY.YY.YYY.....
        ....FFFFFFFFFFFF....
        ...FFFFFFFFFFFFFF...
        ..FFFFFFFFFFFFFFFF..
        ..FFFFFFFFFFFFFFFF..
        ..FFUFUFUFFUFUFUFF..
        ..FF............FF..
        ..FF............FF..
        ..FF............FF..
        """), sitRow: 5)
}
